### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by trougnouf** [GlobalDataverseCommunityConsortium/dataverse-uploader#13]
There is no license set for this repository. This is problematic, eg for packaging.

**Comment by qqmyers** [comment]
Thanks for the ping. The code has included Apache2 for a long time. I just added a top-level LICENSE.md file with the same license.

**Comment by trougnouf** [comment]
Thank you! I've updated https://aur.archlinux.org/packages/dvuploader accordingly.
