### ISSUE TITLE
Error uploading no matter what I try, error: null

### ISSUE THREAD

**Issue by dimyself** [GlobalDataverseCommunityConsortium/dataverse-uploader#16]
Hi there, I dont know what (if anything) i'm doing wrong here...i installed dvuploader on linux

I've tried running this command to upload files against both of these servers:

demo.harvard.edu
dataverse.harvard.edu

It appears to be running some kind of check, and failing...but I have no idea why, it just says "null". I see no documentation either?

I've tried uploading single/multiple files with an absolute or relative path. I've tried different file formats: text, csv, json. I've also tried using different java versions on the system

Heres what I'm running and the log output:

```

DVUploader -server=demo.harvard.edu -key=<my_demo_api_key>  -did=10.70122/FK2/IDN9K3  ./xrp_api_data.txt

----------------------------------------------------------------------------------

TTTTT  DDD   L    Texas
  T    D  D  L    Digital
  T    DDD   LLL  Library

DVUploader - a command-line application to upload files to any Dataverse Dataset
Developed for the Dataverse Community

----------------------------------------------------------------------------------


***Parsing arguments:***

Using server: demo.harvard.edu
Using apiKey: <my_demo_api_key>
Adding content to: 10.70122/FK2/IDN9K3
Request to upload: xrp_api_data.txt

***Starting to Process Upload Requests:***

Error processing check on xrp_api_data.txt : null

PROCESSING(F): xrp_api_data.txt
               Does not yet exist on server.
Error processing /home/<user>/bin/shell/xrp_api_data.txt : null
Not uploaded due to error during processing: xrp_api_data.txt

***Execution Complete.***


```

No matter what options or files or settings I use, i get the exact same error

Thank you!

**Comment by qqmyers** [comment]
From the line `Using apiKey: <my_demo_api_key>`, it looks like you are not swapping in a real API key (which you can get from [https://demo.dataverse.org/dataverseuser.xhtml?selectTab=apiTokenTab](https://demo.dataverse.org/dataverseuser.xhtml?selectTab=apiTokenTab) when you are logged in). The error you are getting is from a call to` server + "/api/datasets/:persistentId/versions/:latest/files?key=" + apiKey  + "&persistentId=" + datasetPID ` which will fail if you aren't using an api key that allows access to the latest (probably draft) version of the dataset you're trying to upload to.

**Comment by dimyself** [comment]
No sorry, i should've made it more clear. I am using real api keys
(generated on dataverse, and the demo site). I just didn't put the actual
key on the issue, because i thought you're not supposed to share the keys.

The command I'm using for apiKey is like:  -key=1234567...... etc etc

Thanks

**Comment by qqmyers** [comment]
OK - how about the -did param including doi: as in -did=doi:10.5072/FK2/TUNNVE ?

**Comment by dimyself** [comment]
Thanks for your reply response... Yes, I tried both with: doi:, and without
it. The log file doesn't have any details that I didn't post. It only says
"null" for an error that I can see

**Comment by qqmyers** [comment]
Hmm - I tried on demo and another server and am seeing something similar - DVUploader is reporting an error, but the file is getting uploaded (i.e. if I refresh the dataset page, the file is there.). I can see an error in the Dataverse server log that suggests a problem during indexing, which shouldn't be a DVUploader problem versus something broken in the API call that DVUploader is using. I'll look into it more tomorrow. 

FWIW: The documentation for DVUploader is at https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/wiki/DVUploader,-a-Command-line-Bulk-Uploader-for-Dataverse .

**Comment by qqmyers** [comment]
@dimyself - I'm going to close this. If you think there's an issue in the DVUploader software/ adding https:// doesn't work for you , we can re-open it (or create a new one). Issues/PRs related to improving the docs and/or command-line param checking would be welcome as well.
