### ISSUE TITLE
link under "About" takes you to a different project

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-uploader#24]
![Screenshot 2023-10-26 at 3 22 31 PM](https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/assets/21006/d785a8b5-52ae-4efe-870a-733480d41dfb)

Clicking takes you to https://github.com/IQSS/dataverse-uploader

**Comment by qqmyers** [comment]
fixed
