### ISSUE TITLE
"ERROR","message":"This file already exists in the dataset

### ISSUE THREAD

**Issue by behinger** [GlobalDataverseCommunityConsortium/dataverse-uploader#9]
Hi!
I ran into a new problem. Some files are not uploaded even though they dont exist.

```
PROCESSING(F): flanker_mobileEEG2021/bids/sub-4/eeg/sub-4_task-FlankerForwardWalking_run-02_channels.tsv
               Does not yet exist on server.
Error response when processing /store/data/sport/flanker_mobileEEG2021/bids/sub-4/eeg/sub-4_task-FlankerForwardWalking_run-02_channels.tsv : Bad Request
{"status":"ERROR","message":"This file already exists in the dataset.  sub-4_task-FlankerForwardWalking_run-02_channels.tsv"}
```

Seems strange to me to say first it does not exist (correct), the say it exists (incorrect).

There is also a warning because some tsv files are "ingested" (but others than where this error occurs, those actually exist). Is there any way to deactive ingestion? Because I dont see the benefit for my data.
Cheers, Bene

**Comment by qqmyers** [comment]
The initial check by DVUploader is by path/name, so if there's no matching file, it says 'Does not exist'. The error when trying to upload indicates that Dataverse thinks a duplicate file does exist. In 4.20, I think Dataverse was still not allowing two files in the same dataset that have the same content (same fixity hash, e.g. MD5). Later versions of Dataverse have relaxed that rule.

Ingesting is done automatically but an admin can set a size limit for ingestion which could be zero.

**Comment by behinger** [comment]
I see, indeed the same file is uploaded multiple times. So I have to contact the administrators of my instance to update the dataverse?

**Comment by qqmyers** [comment]
Yes. FWIW: the [v 5.0 release notes ](https://github.com/IQSS/dataverse/releases/tag/v5.0)discuss the changes for "Updated File Handling".

**Comment by behinger** [comment]
perfect, thanks!
